name: 'Cloud Task'
description: 'A GitHub Action to run a shell script Cloud Task on an IaaS of your choice'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: npm start
      shell: bash

inputs:
  vendor:
    description: 'Cloud Vendor from [vultr, digitalocean, linode]'
    required: true
  api_key:
    description: 'Vendor API key'
    required: true
  task:
    description: 'Shell script to run.'
    required: true